name: Group Board
on:
  pull_request:
    branches: [main, dev]

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm i
      - name: Run Formatting
        run: npm run check

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm i
      - name: Build Project
        run: npm run build
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}
      NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: ${{secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}}
      NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
